filter {
  if "cowrie" in [tags] {

    date {
      match => ["timestamp", "ISO8601"]
      target => "@timestamp"
    }

    if [eventid] == "cowrie.session.connect" {
      mutate { add_field => { "attack_type" => "reconnaissance" } }

    } else if [eventid] == "cowrie.login.success" {
      mutate { add_field => { "attack_type" => "credential_theft" } }

    } else if [eventid] == "cowrie.login.failed" {
      mutate { add_field => { "attack_type" => "bruteforce" } }

    } else if [eventid] == "cowrie.command.input" {
      mutate { add_field => { "attack_type" => "command_injection" } }

    } else {
      mutate { add_field => { "attack_type" => "other_activity" } }
    }
  }
}
